#!/bin/zsh

a=$1

if [[ $1 < 2 ]]; then
	a=1
fi
for (( i = 0; i < $a; i++ )); do
	A=$(shuf -i 1-99999999 -n 1)
	B=$(shuf -i 1-99999999 -n 1)
	C=$(shuf -i 1-99999999 -n 1)
	echo "https://hanime.tv/browse/random?r="$A$B$C
	/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --crash-dumps-dir=/tmp --disable-gpu --headless --dump-dom "https://hanime.tv/browse/random?r="$A$B |grep -o '"/[^"]*"'> ~/html.txt
	sed 's/\"//g' html.txt>list.txt
	filename=list.txt
	declare -a myArray
	myArray=(`cat "$filename"`)
	rm html.txt
	U=$myArray[$(shuf -i 27-49 -n 1)]
	echo "https://hanime.tv"$U
	open "https://hanime.tv"$U
	rm list.txt
done


